### ISSUE TITLE
Library Issues

### ISSUE THREAD

**Issue by HeetShukla** [levkovigor/ppposclient#11]
Hello,

This is Heet Shukla. i try to develop PPPOS Example, but when I Add #include<PPPOS.h> and #include<PPPOSClient.h> i got below Error---->

C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:43:1: error: unknown type name 'ppp_pcb'
ppp_pcb *ppp;
^~~~~~~
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:49:27: error: unknown type name 'ppp_pcb'
static void ppp_status_cb(ppp_pcb *pcb, int err_code, void *ctx)
^~~~~~~
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:149:34: error: unknown type name 'ppp_pcb'
static u32_t ppp_output_callback(ppp_pcb *pcb, u8_t *data, u32_t len, void *ctx)
^~~~~~~
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c: In function 'PPPOS_start':
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:203:47: error: 'ppp_output_callback' undeclared (first use in this function); did you mean 'dns_found_callback'?
ppp = pppapi_pppos_create(&ppp_netif, ppp_output_callback, ppp_status_cb, NULL);
^~~~~~~~~~~~~~~~~~~
dns_found_callback
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:203:47: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:203:68: error: 'ppp_status_cb' undeclared (first use in this function); did you mean 'nvs_stats_t'?
ppp = pppapi_pppos_create(&ppp_netif, ppp_output_callback, ppp_status_cb, NULL);
^~~~~~~~~~~~~
nvs_stats_t
C:\Users\Dell\Documents\Arduino\libraries\PPPOSClient\src\PPPOS.c:210:30: error: 'PPPAUTHTYPE_PAP' undeclared (first use in this function); did you mean 'IP_SET_TYPE_VAL'?
pppapi_set_auth(ppp, PPPAUTHTYPE_PAP, PPP_User, PPP_Pass);
^~~~~~~~~~~~~~~
IP_SET_TYPE_VAL

![image](https://github.com/levkovigor/ppposclient/assets/93855278/0d4a4d42-bc2a-4e96-9a5d-e743655f22eb)

So can you help me Solve these errors.

Thank you
Heet Shukla
E-mail: [heetshukla.89@gmail.com](mailto:heetshukla.89@gmail.com)
Mobile No. : +91 9824390070

**Comment by levkovigor** [comment]
@HeetShukla ESP32-Arduino version should be 2.0.0, or check issue [https://github.com/levkovigor/ppposclient/issues/8](https://github.com/levkovigor/ppposclient/issues/8)

**Comment by HeetShukla** [comment]
I used Arduino version 2.3.2, so I need to change the version?

**Comment by levkovigor** [comment]
@HeetShukla 
I used Arduino version 1.8.19 and ESP32-Arduino version 2.0.0

**Comment by HeetShukla** [comment]
Hello,

I tried on Arduino IDE Version 2.3.2 and Arduino IDE 1.8.19 to Install ESP32 Version 2.0.0 using https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json this and https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json link, but still I’m not able to install ESP32 Version 2.0.0 board. using upper link I got only 2.0.10, 2.0.11, 2.0.15 version board. I’m working on PPPos Library so I need to work on Esp32 version 2.0.0 board. so kindly help me how can I install Esp32 version 2.0.0 board.

**Comment by levkovigor** [comment]
@HeetShukla  with your link it exists

![image](https://github.com/levkovigor/ppposclient/assets/3767544/303e1a00-609e-4b15-8ed5-4c2c4c1ff46b)

**Comment by poultryAppIndia** [comment]
I tried everything and all the suggestions made but no luck. I am using platform.io

`Archiving .pio\build\esp32s3\libe1e\libPpposgsm.a
Linking .pio\build\esp32s3\firmware.elf
c:/users/chait/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32s3/lib722/libPPPOSClient.a(PPPOS.c.o):(.literal.pppos_client_task+0x10): undefined reference to `pppos_input_tcpip'
c:/users/chait/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32s3/lib722/libPPPOSClient.a(PPPOS.c.o): in function `pppos_client_task':
C:\Users\chait\OneDrive\Documents\automate_in_oop/.pio/libdeps/esp32s3/PPPOSClient/src/PPPOS.c:165: undefined reference to `pppos_input_tcpip'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32s3\firmware.elf] Error 1`

here is my platform.ini configuration.

`[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
framework = arduino
monitor_speed = 115200
upload_speed = 921600

# Build flags
build_flags = 
    -Isdkconfig
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_LWIP_PPP_SUPPORT=1
    -D CONFIG_LWIP_PPP_PAP_SUPPORT=1
    -D CONFIG_LWIP_PPP_CHAP_SUPPORT=1
    -D CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=32
    -D CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=1
    -D CONFIG_LWIP_PPPOS_SUPPORT=1
    -DLWIP_PPP_SUPPORT=1
    -DLWIP_SUPPORT_CUSTOM_PPP=1
    -DARDUINO_EVENT_RUNNING_CORE=1


# Libraries
lib_deps = 
    SPI
    https://github.com/Hard-Stuff/TinyGSM.git
    knolleary/PubSubClient@^2.8
    4-20ma/ModbusMaster@^2.0.1
    adafruit/RTClib@^2.1.3
    bblanchon/ArduinoJson@^7.3.0
    plerup/EspSoftwareSerial@^8.2.0
    esp-mqtt
    https://github.com/levkovigor/ppposclient.git`
